name: pet_adobtation_nymble
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  smooth_page_indicator: ^1.1.0
  confetti: ^0.7.0
  alert_banner: ^1.0.1
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  
  assets:
    - assets/petImg/
    - assets/icons/
    - assets/animation/
    - icons/
